name: Build and Deploy HTML from Markdown

on:
  push:
    branches:
      - main  # اینجا می‌توانید نام هر برنچ که مد نظر دارید را مشخص کنید

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if README.md has changed
        id: check_changes
        run: |
          git fetch origin main
          if git diff --exit-code HEAD^ HEAD README.md > /dev/null; then
            echo "README.md has changed"
            echo "::set-output name=has_changed::true"
          else
            echo "README.md has not changed"
            echo "::set-output name=has_changed::false"
          fi

      - name: Install Node.js and markdown-it
        if: steps.check_changes.outputs.has_changed == 'true'
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g markdown-it-cli prismjs

      - name: Convert Markdown to HTML with syntax highlighting
        if: steps.check_changes.outputs.has_changed == 'true'
        run: |
          mkdir -p output
          markdown-it README.md --highlight --html > output/index.html

      - name: Add Prism.js for syntax highlighting
        if: steps.check_changes.outputs.has_changed == 'true'
        run: |
          sed -i '1i <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.27.0/themes/prism-tomorrow.min.css" rel="stylesheet">' output/index.html
          sed -i '1i <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.27.0/prism.min.js"></script>' output/index.html
          sed -i '1i <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.27.0/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js"></script>' output/index.html

      - name: Deploy to GitHub Pages
        if: steps.check_changes.outputs.has_changed == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_COM_TOK }}
          publish_dir: ./output
