name: Convert Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Pandoc
      run: sudo apt-get install pandoc

    - name: Convert Markdown to HTML
      run: pandoc -s -o index.html README.md

    - name: Create a temporary branch and commit
      run: |
        git checkout -b temp-branch  # ایجاد یک شاخه موقت
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Update HTML file"
        git push origin temp-branch  # Push تغییرات به شاخه موقت
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge temporary branch with main
      run: |
        git checkout main  # بازگشت به شاخه اصلی
        git pull origin main  # دریافت آخرین تغییرات
        git merge temp-branch  # ادغام شاخه موقت با شاخه اصلی
        git push origin main  # Push شاخه اصلی
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete temporary branch
      run: |
        git push origin --delete temp-branch  # حذف شاخه موقت از مخزن
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
