name: Convert Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install markdown pygments

    - name: Convert Markdown to HTML
      run: |
        python - <<EOF
        from pygments.lexers import get_lexer_by_name, TextLexer
        from pygments.formatters import HtmlFormatter
        from pygments import highlight
        import markdown
        import re

        
        SVG_COPY = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" viewBox="0 0 24 24" class="icon-sm"><path fill="currentColor" fill-rule="evenodd" d="M7 5a3 3 0 0 1 3-3h9a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3h-2v2a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3v-9a3 3 0 0 1 3-3h2zm2 2h5a3 3 0 0 1 3 3v5h2a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1h-9a1 1 0 0 0-1 1zM5 9a1 1 0 0 0-1 1v9a1 1 0 0 0 1 1h9a1 1 0 0 0 1-1v-9a1 1 0 0 0-1-1z" clip-rule="evenodd"></path></svg>'
        
        # Function to hilight code blocks
        def highlight_codde(code, language):
          try:
            lexer = get_lexer_by_name(language, stripall=True)
          except Exception:
            lexer = TextLexer(stripall=True)

          formatter = HtmlFormatter(cssclass="code-box", style="colorful")
          highlight_code = highlight(code, lexer, formatter)

          code_info = f"""
              <div class="code-info">
                  <div class="code-icon">
                      <button class="copy-icon">
                          {SVG_COPY}
                          <span>Copy code</span>
                      </button>
                  </div>
                  <span class="language">{language}</span>
              </div>
          """
          highlighted_code = re.sub(r'<div class="code-box">', f'<div class="code-box">{code-info}', highlight_code)
          
          return highlighted_code


        # Function to convert markdown to HTML
        def markdown_to_html(md_text):
          # Regex to match code blocks
          code_block_re = re.compile(r"```(\w*)\s*(.*?)\s*```", re.DOTALL | re.MULTILINE)

          # Split code from code language 
          def code_block_replace(match):
            language = match.group(1)
            code = match.group(2).rstrip() # Remove trailing whitespace from code

            return highlight_code(code, language)

          # Convert code block
          html_with_highlight_code = code_block_re.sub(code_block_replacer, md_text)

          # Convert markdown to HTML
          html_content = markdown.markdown(html_with_highlighted_code, extensions=["fenced_code", "codehilite", "tables"])

          return html_content

        # Function to read markdown file and convert to HTML
        def convert_markdown_file(input_file, output_file, title):
          with open(input_file, "r", encoding="utf-8") as file:
            md_text = file.read()

          html_output = markdown_to_html(md_text)

          html_template = f"""
          <!DOCTYPE html>
          <html lang="en" dir="ltr">
          <head>
          <title>My Command</title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <meta name="description" content="The command may be forget">
          <meta name="author" contnt="Ali Ebrahimian">
          <link rel="icon" href="statics/Images/logo.svg" type="image/ico">
          <link rel="stylesheet" type="text/css" href="https://mahd25.github.io/assets/CSS/seasons-style.css">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
          </head>
          <body>
          <main>
              <div class="container">
                  <div class="content">
                      {html_output}
                  </div>
              </div>
          </main>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
            <script src="https://mahd25.github.io/assets/JS/Django-seasons.js"></script>
            <script src="https://mahd25.github.io/assets/JS/copy-icon.js"></script>
          </body>
          </html>
          """

          # Create HTML output
          with open(output_file, "w", encoding="utf-8") as file:
            file.write(html_template)

        convert_markdown_file("README.md", "index.html")
        EOF
  
    - name: Commit HTML file
      run: |
        git config --global user.name "GitHub Acttions"
        git config --global user.email "actions@github.com
        git add -A
        git commit -am "Update HTML file"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_COM_TOK }}

        
