name: Convert Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Pandoc
      run: sudo apt-get install pandoc

    - name: Add custom template
      run: |
        echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>${title}</title>
            <style>
              code {
                white-space: pre-wrap;
                word-wrap: break-word;
                background-color: #f5f5f5;
                padding: 5px;
                border-radius: 5px;
                display: block;
                color: #000;
              }
              pre {
                background-color: #f0f0f0;
                padding: 10px;
                border: 1px solid #ddd;
                border-radius: 5px;
                overflow-x: auto;
              }
              pre > code {
                white-space: pre-wrap;
              }
            </style>
            <link rel="stylesheet" href="statics/style.css">
        </head>
        <body>
            $body$
            <script src="statics/app.js"></script>
        </body>
        </html>' > template.html

    - name: Convert Markdown to HTML with template
      run: pandoc -s -o index.html README.md --template=template.html

    - name: Commit changes to a new branch
      run: |
        git checkout -b update-html
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Update HTML file with custom template"
        git push origin update-html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-html
        title: "Update HTML file"
        body: "This PR updates the HTML file with custom style and script."
