# name: Convert Markdown to HTML

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Pandoc
#       run: sudo apt-get install pandoc

#     - name: Add custom template
#       run: |
#         echo '<!DOCTYPE html>
#         <html lang="en">
#         <head>
#             <meta charset="UTF-8">
#             <meta name="viewport" content="width=device-width, initial-scale=1.0">
#             <title>${title}</title>
#             <link rel="stylesheet" href="statics/style.css">
#         </head>
#         <body>
#             $body$
#             <script src="statics/app.js"></script>
#         </body>
#         </html>' > template.html

#     - name: Convert Markdown to HTML with template
#       run: pandoc -s -o index.html README.md --template=template.html

#     - name: Commit and push changes to main branch
#       run: |
#         git config --global user.name "GitHub Actions"
#         git config --global user.email "actions@github.com"
#         git add index.html
#         git commit -m "Update HTML file with custom template"
#         git pull origin main --rebase
#         git push origin main
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Convert Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install markdown2

    - name: Convert Markdown to HTML using Python
      run: |
        python - <<EOF
        import markdown2
        with open('README.md', 'r') as m:
          md = m.read()
        # md = open('README.md', 'r').read()
        html_content = markdown.markdown(md)
        custom_html = f'''
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>my command</title>
          <link rel="stylesheet" href="statics/style.css">
        </head>
        <body>
          <div class='content'>
            {html_content}
          </div>
          <script src='statics/app.js'></script>
        </body>
        </html>
        '''
        with open('index.html', 'w') as f:
            f.write(custom_html)
        EOF

    - name: Commit HTML file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Update HTML file"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
